books = [
    {
        "id": 1,
        "title": "Surely You're Joking, Mr. Feynman!",
        "author": "Richard P. Feynman",
        "publisher": "W. W. Norton & Company",
        "published_date": "1985-01-01",
        "page_count": 350,
        "language": "English",
    },
    {
        "id": 2,
        "title": "Elon Musk: Tesla, SpaceX, and the Quest for a Fantastic Future",
        "author": "Ashlee Vance",
        "publisher": "HarperCollins",
        "published_date": "2015-05-19",
        "page_count": 400,
        "language": "English",
    },
    {
        "id": 3,
        "title": "A Brief History of Time",
        "author": "Stephen Hawking",
        "publisher": "Bantam Books",
        "published_date": "1988-04-01",
        "page_count": 256,
        "language": "English",
    },
    {
        "id": 4,
        "title": "The Selfish Gene",
        "author": "Richard Dawkins",
        "publisher": "Oxford University Press",
        "published_date": "1976-01-01",
        "page_count": 360,
        "language": "English",
    },
    {
        "id": 5,
        "title": "The Double Helix: A Personal Account of the Discovery of the Structure of DNA",
        "author": "James D. Watson",
        "publisher": "Simon & Schuster",
        "published_date": "1968-02-01",
        "page_count": 256,
        "language": "English",
    },
    {
        "id": 6,
        "title": "Cosmos",
        "author": "Carl Sagan",
        "publisher": "Random House",
        "published_date": "1980-01-01",
        "page_count": 396,
        "language": "English",
    },
]
